version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:0.7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:0.7
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql:0.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  mongodb:
    image: mongo:latest
    ports:
     - 27017:27017
  connect_source:
    image: debezium/connect:0.7
    build:
      context: debezium-mongodb
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
  connect_sink:
    image: debezium/connect-mongodb:0.7
    build:
      context: debezium-mongodb
    ports:
     - 8084:8083
    links:
     - kafka
     - mongodb
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=2
     - CONFIG_STORAGE_TOPIC=my_sink_connect_configs
     - OFFSET_STORAGE_TOPIC=my_sink_connect_offsets
     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
     - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
  aggregator:
    image: debezium/kstreams-aggregator:0.7
    build:
      context: poc-ddd-aggregates
    links:
     - kafka
    environment:
     - JAVA_MAIN_CLASS=io.debezium.examples.aggregation.StreamingAggregatesDDD
     - PARENT_TOPIC=dbserver1.inventory.customers
     - CHILDREN_TOPIC=dbserver1.inventory.addresses
     - BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
     - connect_source
    command: >
      /bin/bash -c "
        while ! curl -f -s -X GET http://connect_source:8083/connectors/mysql-source;
        do
          echo 'Waiting for source connector to be deployed';
          sleep 1;
        done;
        echo 'Source connector deployed!';
        /opt/poc-ddd-aggregates/run-aggregator.sh
      "
